import requests
from bs4 import BeautifulSoup
import feedparser
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import json

# ================= 配置区域 =================
# 如果不需要邮件推送，可以只打印在控制台，或配置钉钉/飞书 Webhook
EMAIL_CONFIG = {
    "enabled": False,  # 改为 True 并填写下方信息以启用邮件推送
    "sender": "your_email@example.com",
    "password": "your_email_smtp_password", # 注意使用应用专用密码
    "receiver": "receiver@example.com",
    "smtp_server": "smtp.example.com",
    "smtp_port": 465
}

DINGTALK_WEBHOOK = None # 如果用钉钉，填入 Webhook URL

# ================= 数据源抓取函数 =================

def get_github_trending():
    """抓取 GitHub Python 领域今日热门项目"""
    print("正在抓取 GitHub Trending...")
    url = "https://github.com/trending/python?since=daily"
    headers = {'User-Agent': 'Mozilla/5.0'}
    try:
        resp = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(resp.text, 'html.parser')
        repos = soup.find_all('article', class_='Box-row')[:5] # 取前5个
        
        results = []
        for repo in repos:
            name = repo.h2.a.get('href').strip()
            desc = repo.p.get_text().strip() if repo.p else "无描述"
            results.append(f"[{name}](https://github.com{name}): {desc}")
        return results
    except Exception as e:
        return [f"GitHub 抓取失败: {e}"]

def get_hf_trending():
    """抓取 Hugging Face 热门模型 (通过 API 模拟或页面抓取)"""
    # HF 没有简单的官方 Trending RSS，这里模拟请求
    print("正在抓取 Hugging Face 热门模型...")
    url = "https://huggingface.co/api/models?sort=trending&limit=5"
    try:
        resp = requests.get(url, timeout=10)
        data = resp.json()
        results = []
        for item in data:
            model_id = item.get('modelId', 'Unknown')
            # 简单获取 pipeline tag (任务类型)
            tag = item.get('pipeline_tag', 'unknown')
            results.append(f"[{model_id}](https://huggingface.co/{model_id}) ({tag})")
        return results
    except Exception as e:
        return [f"Hugging Face 抓取失败: {e}"]

def get_arxiv_cs_cl():
    """抓取 ArXiv CL (Computation and Language) 最新论文"""
    print("正在抓取 ArXiv 论文...")
    # cs.CL 是 NLP/LLM 的主要分类，也可以加 cs.CV
    feed_url = "http://export.arxiv.org/api/query?search_query=cat:cs.CL&start=0&max_results=5&sortBy=submittedDate&sortOrder=descending"
    try:
        feed = feedparser.parse(feed_url)
        results = []
        for entry in feed.entries:
            title = entry.title
            link = entry.link
            # 简单的摘要截取
            summary = entry.summary.replace('\n', ' ')[:100] + "..."
            results.append(f"[{title}]({link})\n> {summary}")
        return results
    except Exception as e:
        return [f"ArXiv 抓取失败: {e}"]

# ================= 推送功能 =================

def send_email(subject, content):
    if not EMAIL_CONFIG["enabled"]:
        return
    
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = EMAIL_CONFIG["sender"]
    msg['To'] = EMAIL_CONFIG["receiver"]
    
    # 将 Markdown 转为简单的 HTML (邮件支持 HTML 会更好看)
    # 这里简单处理，实际可以用 markdown 库转换
    html_content = content.replace('\n', '<br>')
    msg.attach(MIMEText(html_content, 'html', 'utf-8'))
    
    try:
        with smtplib.SMTP_SSL(EMAIL_CONFIG["smtp_server"], EMAIL_CONFIG["smtp_port"]) as server:
            server.login(EMAIL_CONFIG["sender"], EMAIL_CONFIG["password"])
            server.send_message(msg)
        print("邮件发送成功")
    except Exception as e:
        print(f"邮件发送失败: {e}")

def send_dingtalk(content):
    if not DINGTALK_WEBHOOK:
        return
    headers = {"Content-Type": "application/json"}
    data = {
        "msgtype": "markdown",
        "markdown": {
            "title": "AI Daily Report",
            "text": content
        }
    }
    try:
        requests.post(DINGTALK_WEBHOOK, headers=headers, data=json.dumps(data))
        print("钉钉推送成功")
    except Exception as e:
        print(f"钉钉推送失败: {e}")

# ================= 主逻辑 =================

def generate_report():
    today = datetime.now().strftime("%Y-%m-%d")
    report = f"# 🤖 AI Daily Report - {today}\n\n"
    
    report += "## 🔥 GitHub Trending (Python/AI)\n"
    report += "最新开源工具和框架：\n"
    for item in get_github_trending():
        report += f"1. {item}\n"
    
    report += "\n## 🤗 Hugging Face Trending Models\n"
    report += "社区最热模型：\n"
    for item in get_hf_trending():
        report += f"1. {item}\n"
        
    report += "\n## 📄 ArXiv Latest (cs.CL/LLM)\n"
    report += "最新论文速递：\n"
    for item in get_arxiv_cs_cl():
        report += f"1. {item}\n\n"
        
    report += "\n---\n*Generated by AI Engineer Daily Script*"
    
    return report

if __name__ == "__main__":
    report_content = generate_report()
    print(report_content) # 打印到控制台
    
    # 发送通知
    send_email(f"AI Daily Report - {datetime.now().strftime('%m-%d')}", report_content)
    send_dingtalk(report_content)
